---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-ocp-ai
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: ba708aed-bb8a-4ac0-83a7-53a066701db5
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
